apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-crash
  labels:
    app: busybox-crash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-crash
  template:
    metadata:
    labels:
      app: busybox-crash
  spec:
    containers:
    - name: busybox
      image: busybox:latest
      command: ["sh", "-c", "echo 'Starting...'; sleep 100; echo 'Exiting...'; exit 1"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
    restartPolicy: Always # This is default